### ISSUE TITLE
Composite keys seem to fail with Laravel

### ISSUE THREAD

**Issue by Zemke** [Zemke/tippspiel#15]
The exception when a bet is saved for the time is down below. Interestingly it works without problems when submit is clicked the second time. This might be a relevant issue: laravel/framework#5248

```
[2016-05-24 20:08:20] local.ERROR: exception 'ErrorException' with message 'PDO::lastInsertId() expects parameter 1 to be string, array given' in /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php:34
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'PDO::lastInsert...', '/Users/Zemke/Co...', 34, Array)
#1 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(34): PDO->lastInsertId(Array)
#2 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1821): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `be...', Array, Array)
#3 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, Array)
#4 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1015): call_user_func_array(Array, Array)
#5 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1592): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#6 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1592): Illuminate\Database\Eloquent\Builder->insertGetId(Array, Array)
#7 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1561): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#8 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1452): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#9 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(193): Illuminate\Database\Eloquent\Model->save()
#10 [internal function]: Illuminate\Database\Eloquent\Builder->updateOrCreate(Array, Array)
#11 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3437): call_user_func_array(Array, Array)
#12 [internal function]: Illuminate\Database\Eloquent\Model->__call('updateOrCreate', Array)
#13 [internal function]: Todo\Bet->updateOrCreate(Array, Array)
#14 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(3451): call_user_func_array(Array, Array)
#15 /Users/Zemke/Code/tippspiel/app/Http/Controllers/BetController.php(61): Illuminate\Database\Eloquent\Model::__callStatic('updateOrCreate', Array)
#16 /Users/Zemke/Code/tippspiel/app/Http/Controllers/BetController.php(61): Todo\Bet::updateOrCreate(Array, Array)
#17 [internal function]: Todo\Http\Controllers\BetController->store(Object(Illuminate\Http\Request))
#18 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#19 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): Illuminate\Routing\Controller->callAction('store', Array)
#20 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(Todo\Http\Controllers\BetController), Object(Illuminate\Routing\Route), 'store')
#21 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#22 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#26 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(Todo\Http\Controllers\BetController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'store')
#27 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(203): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'Todo\\Http\\Contr...', 'store')
#28 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#29 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(708): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#30 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#31 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#32 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#34 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(710): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#35 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(675): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#36 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#37 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#38 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#39 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#40 /Users/Zemke/Code/tippspiel/vendor/barryvdh/laravel-cors/src/HandleCors.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#41 [internal function]: Barryvdh\Cors\HandleCors->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#43 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#44 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#46 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#49 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#50 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#52 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#53 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#54 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#55 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(44): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#57 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#58 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#60 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#61 /Users/Zemke/Code/tippspiel/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#62 /Users/Zemke/Code/tippspiel/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#63 {main}  
```

**Comment by Zemke** [comment]
It does actually correctly save and update, but the exception is still unpleasant.
